# Generated by Django 5.0.2 on 2024-02-08 19:02

import parkIndex.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkIndex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(default=parkIndex.models.generate_random_alphanumeric, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.CharField(default=parkIndex.models.generate_random_alphanumeric, max_length=10, primary_key=True, serialize=False),
        ),
    ]
